### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-Aravind-shrenivas#1]
Dear aravind-shrenivas -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

You attempted to add interpretation, so I gave you the 1/2 credit on narrative scores that I promised. 

Your score is **8.5/10**

---

### Training and Data: `[8 / 10 points]`

- Reasonable choice for classification: `[6 / 6 points]`
- Narrative: `[2 / 4 points]`
- Feedback: [Insert feedback here.]

### Fitting classification models: `[19 / 22 points]`

  - Correct application: `[16 / 16]`
  - Narrative `[3 / 6]`
  - Feedback: [Insert feedback here.]

### Comparing models: `[7.5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[2.5 / 5]`
  - Feedback: [Insert feedback here.]

### Applying chosen model: `[7.5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[2.5 / 5]`
  - Feedback: [Insert feedback here.]

### Comparing decision boundaries: `[23 / 28 points]`

  - Correct application: `[18 / 18]`
  - Narrative: `[5 / 10]`
  - Feedback: [Insert feedback here.]

### Overall: `[_ / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [ ] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by Aravind-shrenivas** [comment]
Thank you Greg.
